# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Checkin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: 0 */6 * * *

jobs:

  Yuki-Glados-Checkin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run
      run: |
          sudo ./checkin ${{ secrets.koaSess }} ${{ secrets.koaSessSig }} ${{ secrets.email }}
